http:
  routers:
    router-http-ghost:
      rule: "Host(`example.com`) || Host(`www.example.com`)"
      entryPoints:
        - "web"
#      middlewares:
#        - "redirect-to-https" 
      service: "ghost-blog"
      
    router-http-nextcloud:
      rule: "Host(`nextcloud.example.com`)"
      entryPoints:
        - "web"
#      middlewares:
#        - "redirect-to-https" 
      service: "nextcloud"

    router-http-qnap:
      rule: "Host(`qnap.example.com`)"
      entryPoints:
        - "web"
#      middlewares:
#        - "redirect-to-https" 
      service: "qnap"

    router-ghost:
      entryPoints:
        - "websecure"
      rule: "Host(`example.com`) || Host(`www.example.com`)"
      tls:
        certResolver: myresolver
      service: "ghost-blog"  
   
    router-nextcloud:
      entryPoints:
        - "websecure"
      rule: "Host(`nextcloud.example.com`)"
      tls:
        certResolver: myresolver
      service: "nextcloud"  

    router-qnap:
      entryPoints:
        - "websecure"
      rule: "Host(`qnap.example.com`)"
      tls:
        certResolver: myresolver
      service: "qnap"  
    
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    ghost-blog:
      loadBalancer:
        servers:
        - url: "http://10.10.10.5:2368"
        
    nextcloud:
      loadBalancer:
        servers:
        - url: "http://10.10.10.7:80"    
        
    qnap:
      loadBalancer:
        servers:
        - url: "http://<localip>:8080"
        
# If you rather use the server's own https, bypass traefik
#tcp:
#  routers:
#    router-qnap-https:
#      entryPoints:
#        - "websecure"
#      rule: "HostSNI(`qnap.example.com`)"
#      tls:
#        passthrough: true
#      service: "qnap-https"
#    
#    router-nextcloud-https:
#      entryPoints:
#        - "websecure"
#      rule: "HostSNI(`nextcloud.example.com`)"
#      tls:
#        passthrough: true
#      service: "nextcloud-https"
#
#  services:
#    qnap-https:
#      loadBalancer:
#        servers:
#        - address: "<localip>:443"
#    nextcloud-https:
#      loadBalancer:
#        servers:
#        - address: "<localip>:443"
